/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import DataSet.Dspendaftar;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class framependaftar extends javax.swing.JFrame {
    
    Dspendaftar DataSetpendaftar;

    /**
     * Creates new form framependaftar
     */
    public framependaftar() {
        initComponents();
        this.setLocationRelativeTo(null);
        DataSetpendaftar=new Dspendaftar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnopendaftaran = new javax.swing.JTextField();
        txttgldaftar = new javax.swing.JTextField();
        txtthnakademik = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttmptlhr = new javax.swing.JTextField();
        txttgllhr = new javax.swing.JTextField();
        txtagama = new javax.swing.JTextField();
        txtalmttlpn = new javax.swing.JTextField();
        txtkodepos = new javax.swing.JTextField();
        txtnamaayah = new javax.swing.JTextField();
        txtnamaibu = new javax.swing.JTextField();
        txtpekerjaan = new javax.swing.JTextField();
        txtalmtortu = new javax.swing.JTextField();
        txtasalsklh = new javax.swing.JTextField();
        txtcarapendaftaran = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnbaca = new javax.swing.JButton();
        cmdsttsdaftar = new javax.swing.JComboBox<>();
        cmdjk = new javax.swing.JComboBox<>();
        cmdthnlulus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PENDAFTAR");

        jLabel2.setText("No Pendaftaran");

        jLabel3.setText("Tanggal Daftar");

        jLabel4.setText("Tahun Akademik ");

        jLabel5.setText("Nama");

        jLabel6.setText("Tempat Lahir");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("Jenis Kelamin");

        jLabel9.setText("Agama");

        jLabel10.setText("Alamat Telepon");

        jLabel11.setText("Kode Pos");

        jLabel12.setText("Nama Ayah");

        jLabel13.setText("Nama Ibu");

        jLabel14.setText("Pekerjaan");

        jLabel15.setText("Alamat Ortu");

        jLabel16.setText("Asal Sekolah");

        jLabel17.setText("Tahun Lulus");

        jLabel18.setText("Cara Pendaftaran");

        jLabel19.setText("Status Daftar");

        txttgldaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgldaftarActionPerformed(evt);
            }
        });

        txtthnakademik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthnakademikActionPerformed(evt);
            }
        });

        btntambah.setText("TAMBAH DATA");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnbaca.setText("BACA DATA");
        btnbaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacaActionPerformed(evt);
            }
        });

        cmdsttsdaftar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Terdaftar", "Tidak Terdaftar", " " }));

        cmdjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-Laki", "Perempuan" }));

        cmdthnlulus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "2018-2019", "2020-2021", "2022-2023" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btntambah)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnbaca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnopendaftaran)
                                    .addComponent(txttgldaftar)
                                    .addComponent(txtthnakademik)
                                    .addComponent(txtnama)
                                    .addComponent(txttmptlhr)
                                    .addComponent(txttgllhr)
                                    .addComponent(txtagama)
                                    .addComponent(txtalmttlpn)
                                    .addComponent(txtkodepos)
                                    .addComponent(txtnamaayah)
                                    .addComponent(txtnamaibu)
                                    .addComponent(txtpekerjaan)
                                    .addComponent(txtalmtortu)
                                    .addComponent(txtasalsklh)
                                    .addComponent(txtcarapendaftaran)
                                    .addComponent(cmdsttsdaftar, 0, 161, Short.MAX_VALUE)
                                    .addComponent(cmdjk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmdthnlulus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnopendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txttgldaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtthnakademik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txttmptlhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txttgllhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmdjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtalmttlpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtnamaayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtnamaibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtalmtortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtasalsklh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdthnlulus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcarapendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(cmdsttsdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnbaca))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttgldaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgldaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgldaftarActionPerformed

    private void txtthnakademikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthnakademikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthnakademikActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        DataSetpendaftar.nopendaftaran(Integer.valueOf(txtnopendaftaran.getText()));
        DataSetpendaftar.tgldaftar(txttgldaftar.getText());
        DataSetpendaftar.thnakademik(txtthnakademik.getText());
        DataSetpendaftar.nama(txtnama.getText());
        DataSetpendaftar.tmptlahir(txttmptlhr.getText());
        DataSetpendaftar.tgllahir(txttgllhr.getText());
        DataSetpendaftar.jeniskelamin(cmdjk.getSelectedItem().toString());
        DataSetpendaftar.agama(txtagama.getText());
        DataSetpendaftar.alamattlpn(txtalmttlpn.getText());
        DataSetpendaftar.kodepos(Integer.valueOf(txtkodepos.getText()));
        DataSetpendaftar.namaayah(txtnamaayah.getText());
        DataSetpendaftar.namaibu(txtnamaibu.getText());
        DataSetpendaftar.pekerjaan(txtpekerjaan.getText());
        DataSetpendaftar.alamatortu(txtalmtortu.getText());
        DataSetpendaftar.asalsekolah(txtasalsklh.getText());
        DataSetpendaftar.tahunlulus(cmdthnlulus.getSelectedItem().toString());
        DataSetpendaftar.carapendaftaran(txtcarapendaftaran.getText());
        DataSetpendaftar.statusdaftar(cmdsttsdaftar.getSelectedItem().toString());
        
        String pesan = "Data Berhasil Disimpan ke Array";
        JOptionPane.showMessageDialog(this, pesan);
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnbacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacaActionPerformed
        String isipesan = "No Pendaftaran : " + DataSetpendaftar.getDataSetnopendaftaran().get(0)+
                          "\nTgl Daftar : " + DataSetpendaftar.getDataSettgldaftar().get(0)+
                          "\nThn Akademik : " + DataSetpendaftar.getDataSetthnakademik().get(0)+
                          "\nNama : " + DataSetpendaftar.getDataSetnama().get(0)+
                          "\nTmpt Lahir : " + DataSetpendaftar.getDataSettmptlahir().get(0)+
                          "\nTgl Lahir : " + DataSetpendaftar.getDataSettgllahir().get(0)+
                          "\nJenis Kelamin : " + DataSetpendaftar.getDataSetjeniskelamin().get(0)+
                          "\nAgama : " + DataSetpendaftar.getDataSetagama().get(0)+
                          "\nAlamat Telepon : " + DataSetpendaftar.getDataSetalamattlpn().get(0)+
                          "\nKode Pos : " + DataSetpendaftar.getDataSetkodepos().get(0)+
                          "\nNama Ayah : " + DataSetpendaftar.getDataSetnamaayah().get(0)+
                          "\nNama Ibu : " + DataSetpendaftar.getDataSetnamaibu().get(0)+
                          "\nPekerjaan : " + DataSetpendaftar.getDataSetpekerjaan().get(0)+
                          "\nAlamat Ortu : " + DataSetpendaftar.getDataSetalamatortu().get(0)+
                          "\nAsal Sekolah : " + DataSetpendaftar.getDataSetasalsekolah().get(0)+
                          "\nThn Lulus : " + DataSetpendaftar.getDataSettahunlulus().get(0)+
                          "\nCara Pendaftaran : " + DataSetpendaftar.getDataSetcarapendaftaran().get(0)+
                          "\nStatus Daftar : " + DataSetpendaftar.getDataSetstatusdaftar().get(0);
        JOptionPane.showMessageDialog(this, isipesan);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framependaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framependaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framependaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framependaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framependaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaca;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmdjk;
    private javax.swing.JComboBox<String> cmdsttsdaftar;
    private javax.swing.JComboBox<String> cmdthnlulus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextField txtalmtortu;
    private javax.swing.JTextField txtalmttlpn;
    private javax.swing.JTextField txtasalsklh;
    private javax.swing.JTextField txtcarapendaftaran;
    private javax.swing.JTextField txtkodepos;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamaayah;
    private javax.swing.JTextField txtnamaibu;
    private javax.swing.JTextField txtnopendaftaran;
    private javax.swing.JTextField txtpekerjaan;
    private javax.swing.JTextField txttgldaftar;
    private javax.swing.JTextField txttgllhr;
    private javax.swing.JTextField txtthnakademik;
    private javax.swing.JTextField txttmptlhr;
    // End of variables declaration//GEN-END:variables
}
